### ISSUE TITLE
Milestones for v8 updates

### ISSUE THREAD

**Issue by natgeo-wong** [natgeo-wong/GeoRegions.jl#12]
In `v8` of GeoRegions.jl, I'm going to cast aside the old `RectRegion`, `PolyRegion` and `TiltRegion` types and make them a bit more generalizable. I also hope to be able to add functionality such that a `GeoRegion` can contain multiple regions. This would be very useful if we want to use GeoRegions.jl to analyze data for **countries**.

# Milestones for GeoRegion Types
- [x] Merge all current Types into a single `GeoRegion` Type
- [x] Rewrite documentation to suit (should not be too bad, only about creation and reading)

# Milestones for Project Handling
- [x] Instead of lists in textfiles, each `GeoRegion` will have its own separate JSON file that contains: (a) ID, (b) pID, (c) name, (d) rotation, (e) longitude points and (f) latitude points, and this would prevent excessive reading/writing when there are many hundreds of GeoRegions in a project
- [x] put custom GeoRegions into a distinct folder in `path`, so `GeoRegion(..., save = true, path = pwd())` means that the information on the GeoRegions will be saved into `path = joinpath(pwd(),".georegions")`

# Optional Milestones
- [ ] Shapefiles!
- [ ] Add in NaturalEarth stuff (OceanBasin regions, country boundaries)?
- [ ] `MultipleRegion` type, which allows for the combination of multiple polygonal regions into a single GeoRegion

**Comment by natgeo-wong** [comment]
v8 has been merged into the Julia Registry. (https://github.com/JuliaRegistries/General/pull/125144)

All optional milestones will come in future minor releases.
